// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValhallaVault.Data;

#nullable disable

namespace ValhallaVault.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240311134607_mg")]
    partial class mg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ValhallaVault.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ValhallaVault.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Att skydda sig mot bedrägerier",
                            Description = "Syftar på att ta försiktighetsåtgärder för att undvika att bli lurad eller manipulerad av bedrägliga aktiviteter eller människor. Det innebär att vara medveten om potentiella risker, att vara försiktig med personlig information och att utveckla strategier för att identifiera och undvika bedrägerier"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Cybersäkerhet för företag",
                            Description = "Detta innebär att implementera en serie av säkerhetsåtgärder och bästa praxis för att skydda företagets digitala tillgångar, information och system från cyberhot och attacker. Det omfattar vanligtvis användningen av tekniska lösningar som brandväggar, antivirusprogram, kryptering och säkerhetskopiering, samt etablering av säkerhetspolicyer och rutiner för att hantera risker och incidenter."
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Cyberspionage",
                            Description = "Cyberspionage är en form av spionage där angripare använder digitala metoder för att infiltrera och stjäla konfidentiell information från organisationer, myndigheter eller enskilda individer. Det innebär vanligtvis användning av avancerade tekniker såsom malware, phishing och social engineering för att få tillgång till känslig data utan att upptäckas."
                        });
                });

            modelBuilder.Entity("ValhallaVault.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Options = "[\"Ett legitimt f\\u00F6rs\\u00F6k fr\\u00E5n banken att skydda ditt konto\",\"En informationsinsamling f\\u00F6r en marknadsunders\\u00F6kning\",\"Ett potentiellt telefonbedr\\u00E4geri\"]",
                            Question = "Du får ett oväntat telefonsamtal från någon som påstår sig vara från din bank. Personen ber dig bekräfta ditt kontonummer och lösenord för att säkerställa din kontos säkerhet efter en påstådd säkerhetsincident. Hur bör du tolka denna situation?",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Options = "[\"Ge dem informationen de ber om, f\\u00F6r s\\u00E4kerhets skull\",\"Avsluta samtalet och kontakta din bank direkt via ett officiellt nummer du vet \\u00E4r korrekt\",\"V\\u00E4nta p\\u00E5 att de ska ringa tillbaka f\\u00F6r att bekr\\u00E4fta deras legitimitet\"]",
                            Question = "Vad bör du göra omedelbart efter att ha mottagit ett misstänkt telefonsamtal där någon frågar efter personlig finansiell information?",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Options = "[\"Banker skickar ofta e-postmeddelanden som ber kunder att direkt ange l\\u00F6senord och kontonummer f\\u00F6r verifiering.\",\"Banker ringer regelbundet sina kunder f\\u00F6r att be dem upprepa sina kontouppgifter f\\u00F6r s\\u00E4kerhetsuppdateringar.\",\"Banker och finansiella institutioner kommer aldrig att be dig om ditt l\\u00F6senord eller kontonummer via telefon eller e-post.\"]",
                            Question = "Vilket av följande påståenden är sant angående hur finansiella institutioner kommunicerar med sina kunder?",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Options = "[\"Installera en app som blockerar misst\\u00E4nkta samtal\",\"Aldrig svara p\\u00E5 samtal fr\\u00E5n ok\\u00E4nda nummer\",\"Uppr\\u00E4tta starka s\\u00E4kerhetsfr\\u00E5gor med din bank som kr\\u00E4vs f\\u00F6r att identifiera dig \\u00F6ver telefon\"]",
                            Question = "Hur kan du bäst skydda dig mot telefonbedrägerier",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Options = "[\"En legitim beg\\u00E4ran om hj\\u00E4lp fr\\u00E5n en person i n\\u00F6d\",\"Ett romansbedr\\u00E4geri\",\"En tillf\\u00E4llig ekonomisk sv\\u00E5righet\"]",
                            Question = "Efter flera månader av daglig kommunikation med någon du träffade på en datingsida, börjar personen berätta om en plötslig finansiell kris och ber om din hjälp genom att överföra pengar. Vad indikerar detta mest sannolikt?",
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 6,
                            Options = "[\"Genomf\\u00F6ra omedelbar investering f\\u00F6r att inte missa m\\u00F6jligheten\",\"Investeringsbedr\\u00E4geri\",\"Beg\\u00E4ra mer information f\\u00F6r att utf\\u00F6ra en noggrann \\u2018\\u2019due diligence\\u2019\"]",
                            Question = "Du får ett e-postmeddelande/samtal om ett exklusivt erbjudande att investera i ett startup-företag som påstås ha en revolutionerande ny teknologi, med garantier om exceptionellt hög avkastning på mycket kort tid. Hur bör du förhålla dig till erbjudandet?",
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            Options = "[\"Ett misstag av kreditkortsf\\u00F6retaget\",\"Kreditkortsbedr\\u00E4geri\",\"Obeh\\u00F6riga k\\u00F6p av en familjemedlem\"]",
                            Question = "Efter en online-shoppingrunda märker du oidentifierade transaktioner på ditt kreditkortsutdrag från företag du aldrig handlat från. Vad indikerar detta mest sannolikt?",
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 8,
                            Options = "[\"Utbildning i digital s\\u00E4kerhet f\\u00F6r alla anst\\u00E4llda\",\"Installera en starkare brandv\\u00E4gg\",\"Byta ut all IT-utrustning\"]",
                            Question = "Inom företaget märker man att konfidentiella dokument regelbundet läcker ut till konkurrenter. Efter en intern granskning upptäcks det att en anställd omedvetet har installerat skadlig programvara genom att klicka på en länk i ett phishing-e-postmeddelande. Vilken åtgärd bör prioriteras för att förhindra framtida incidenter?",
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 9,
                            Options = "[\"Manuellt kontrollera varje anst\\u00E4llds l\\u00F6senord en g\\u00E5ng per \\u00E5r\",\"Implementera en policy f\\u00F6r l\\u00F6senordskomplexitet som kr\\u00E4ver automatiska l\\u00F6senords\\u00E4ndringar var 90:e dag\",\"Uppmana anst\\u00E4llda att v\\u00E4lja l\\u00E4ttih\\u00E5gda l\\u00F6senord f\\u00F6r att undvika att skriva ner dem\"]",
                            Question = "Vilken åtgärd är mest effektiv för att säkerställa att anställda regelbundet uppdaterar sina lösenord till starkare och mer komplexa versioner?",
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 10,
                            Options = "[\"F\\u00F6rbjuda anv\\u00E4ndning av offentliga Wi-Fi-n\\u00E4tverk helt och h\\u00E5llet\",\"Utrusta alla anst\\u00E4lldas enheter med VPN (Virtual Private Network)-tj\\u00E4nster\",\"Endast till\\u00E5ta anst\\u00E4llda att arbeta offline n\\u00E4r de inte \\u00E4r p\\u00E5 kontoret\"]",
                            Question = "Hur kan företaget effektivt minska risken för att anställda oavsiktligt exponerar företagsdata via otrygga Wi-Fi-nätverk?",
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 11,
                            Options = "[\"Blockera all inkommande e-post fr\\u00E5n externa k\\u00E4llor\",\"Installera och uppdatera regelbundet e-posts\\u00E4kerhetsl\\u00F6sningar som filtrerar bort skadlig programvara och misst\\u00E4nkta l\\u00E4nkar\",\"L\\u00E5ta anst\\u00E4llda anv\\u00E4nda personliga e-postkonton f\\u00F6r arbete f\\u00F6r att minska risken f\\u00F6r f\\u00F6retagets e-postservers s\\u00E4kerhet\"]",
                            Question = "Vilken åtgärd bör ett företag ta för att skydda sig mot intrång via e-postbaserade hot som phishing?",
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 12,
                            Options = "[\"Informera alla anv\\u00E4ndare om s\\u00E5rbarheten och rekommendera tempor\\u00E4ra skydds\\u00E5tg\\u00E4rder\",\"Ignorera problemet tills en patch kan utvecklas\",\"St\\u00E4nga ner tj\\u00E4nsten tillf\\u00E4lligt\"]",
                            Question = "Inom företaget upptäckts det en sårbarhet i vår programvara som kunde möjliggöra obehörig åtkomst till användardata. Företaget har inte omedelbart en lösning. Vilken är den mest lämpliga första åtgärden?",
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 13,
                            Options = "[\"En enskild hackare med ett personligt vendetta\",\"En konkurrerande f\\u00F6retagsentitet\",\"Organiserade cyberbrottsliga grupper\"]",
                            Question = "Vårt företag blir måltavla för en DDoS-attack som överväldigar våra servers och gör våra tjänster otillgängliga för kunder. Vilken typ av aktör är mest sannolikt ansvarig för denna typ av attack?",
                            SubcategoryId = 14
                        },
                        new
                        {
                            Id = 14,
                            Options = "[\"\\u00C5terg\\u00E5 till kontorsarbete\",\"Inf\\u00F6ra striktare l\\u00F6senordspolicyer och tv\\u00E5faktorsautentisering f\\u00F6r fj\\u00E4rr\\u00E5tkomst\",\"F\\u00F6rbjuda anv\\u00E4ndning av personliga enheter f\\u00F6r arbete\"]",
                            Question = "Med övergången till distansarbete upptäcker vårt företag en ökning av säkerhetsincidenter, inklusive obehörig åtkomst till företagsdata. Vilken åtgärd bör företaget vidta för att adressera denna nya riskmiljö?",
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 15,
                            Options = "[\"Phishing\",\"Ransomware\",\"Spyware\"]",
                            Question = "Hälsovårdsmyndigheten utsätts för ett cyberangrepp som krypterar patientdata och kräver lösen för att återställa åtkomsten. Vilken typ av angrepp har de sannolikt blivit utsatta för?",
                            SubcategoryId = 16
                        },
                        new
                        {
                            Id = 16,
                            Options = "[\"Spyware\",\"Ransomware\",\"Adware\"]",
                            Question = "Det globala fraktbolaget Maersk blev offer för ett omfattande cyberangrepp som avsevärt störde deras verksamhet världen över. Vilken typ av malware var primärt ansvarig för denna incident?",
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 17,
                            Options = "[\"Cyberkriminalitet\",\"Cyberspionage\",\"Cyberterrorism\"]",
                            Question = "Regeringen upptäcker att känslig politisk kommunikation har läckt och misstänker elektronisk övervakning. Vilket fenomen beskriver bäst denna situation?",
                            SubcategoryId = 36
                        },
                        new
                        {
                            Id = 18,
                            Options = "[\"\\u00D6ka anv\\u00E4ndningen av kryptering f\\u00F6r all intern och extern kommunikation\",\"F\\u00F6rbjuda all anv\\u00E4ndning av e-post och \\u00E5terg\\u00E5 till fysisk korrespondens\",\"Installera antivirusprogram p\\u00E5 alla datorer\"]",
                            Question = "Vilken försvarsstrategi är mest effektiv mot cyberspionage som riktar sig mot känslig kommunikation?",
                            SubcategoryId = 36
                        },
                        new
                        {
                            Id = 19,
                            Options = "[\"Genomf\\u00F6ra strikta bakgrundskontroller av alla anst\\u00E4llda\",\"Implementera ett omfattande program f\\u00F6r beteendeanalys och anomalidetektering\",\"Begr\\u00E4nsa internetanv\\u00E4ndningen p\\u00E5 arbetsplatsen till arbetsrelaterade aktiviteter\"]",
                            Question = "Hur kan organisationer bäst upptäcka och motverka insiderhot som bidrar till cyberspionage?",
                            SubcategoryId = 36
                        },
                        new
                        {
                            Id = 20,
                            Options = "[\"Genomf\\u00F6ra regelbundna medvetenhetstr\\u00E4ningar f\\u00F6r alla anst\\u00E4llda om cybers\\u00E4kerhet\",\"H\\u00E5lla all mjukvara och operativsystem uppdaterade med de senaste s\\u00E4kerhetspatcharna\",\"Endast anv\\u00E4nda egenutvecklad mjukvara f\\u00F6r alla verksamhetsprocesser\"]",
                            Question = "Vilken åtgärd är viktigast för att skydda sig mot cyberspionage genom utnyttjande av mjukvarusårbarheter?",
                            SubcategoryId = 36
                        },
                        new
                        {
                            Id = 21,
                            Options = "[\"Social ingenj\\u00F6rskonst\",\"Mass\\u00F6vervakning\",\"Riktade cyberattacker\"]",
                            Question = "Regeringen blir varse om en sofistikerad skadeprogramskampanj som utnyttjar Zero-day sårbarheter för att infiltrera deras nätverk och stjäla oerhört viktig data. Vilken metod för cyberspionage används sannolikt här?",
                            SubcategoryId = 37
                        },
                        new
                        {
                            Id = 22,
                            Options = "[\"GDPR\",\"S\\u00E4kerhetsskyddslagen\",\"IT-s\\u00E4kerhetslagen\"]",
                            Question = "Regeringen i Sverige ökar sitt interna säkerhetsprotokoll för att skydda sig mot utländska underrättelsetjänsters infiltration. Vilken lagstiftning ger ramverket för detta skydd?",
                            SubcategoryId = 38
                        },
                        new
                        {
                            Id = 23,
                            Options = "[\"Oberoende hackare\",\"Aktivistgrupper\",\"Statssponsrade hackers\"]",
                            Question = "Lunds universitet upptäcker att forskningsdata om ny teknologi har stulits. Undersökningar tyder på en välorganiserad grupp med kopplingar till en utländsk stat. Vilken typ av aktör ligger sannolikt bakom detta?",
                            SubcategoryId = 39
                        });
                });

            modelBuilder.Entity("ValhallaVault.Models.ResultModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("ResultModel");
                });

            modelBuilder.Entity("ValhallaVault.Models.SegmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Segments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            SegmentName = "Del 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            SegmentName = "Del 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            SegmentName = "Del 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            SegmentName = "Del 1"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            SegmentName = "Del 2"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            SegmentName = "Del 3"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            SegmentName = "Del 4"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            SegmentName = "Del 1"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            SegmentName = "Del 2"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            SegmentName = "Del 3"
                        });
                });

            modelBuilder.Entity("ValhallaVault.Models.SolutionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("Solutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "Ett potentiellt telefonbedrägeri",
                            Explanation = "Banker och andra finansiella institutioner begär aldrig känslig information såsom kontonummer eller lösenord via telefon. Detta är ett klassiskt tecken på telefonbedrägeri.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "Avsluta samtalet och kontakta din bank direkt via ett officiellt nummer du vet är korrekt.",
                            Explanation = "Det säkraste sättet att hantera potentiella telefonbedrägerier är att avsluta samtalet och sedan själv ringa upp din bank via ett telefonnummer du vet är korrekt (till exempel från deras officiella webbplats eller ditt bankkort) för att verifiera om samtalet var legitimt.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "Banker och finansiella institutioner kommer aldrig att be dig om ditt lösenord eller kontonummer via telefon eller e-post.",
                            Explanation = "Kommunikationen från banker och finansiella institutioner innehåller aldrig förfrågningar om känslig information som lösenord eller kontonummer via osäkra kanaler som telefon eller e-post. Detta är en grundläggande säkerhetsprincip.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "Upprätta starka säkerhetsfrågor med din bank som krävs för att identifiera dig över telefon",
                            Explanation = "Genom att ha förutbestämda säkerhetsfrågor med din bank kan du och banken ha en säker metod för att bekräfta varandras identitet under telefonsamtal. Detta minskar risken för att bli lurad av bedragare som inte kan svara på dessa frågor.\r\n",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "Ett romansbedrägeri",
                            Explanation = "Begäran om pengar, särskilt under omständigheter där två personer aldrig har träffats fysiskt, är ett vanligt tecken på romansbedrägeri",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "Investeringsbedrägeri",
                            Explanation = "Erbjudanden som lovar hög avkastning med liten eller ingen risk, särskilt via oönskade e-postmeddelanden, är ofta tecken på investeringsbedrägerier.",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswer = "Kreditkortsbedrägeri",
                            Explanation = "Oidentifierade transaktioner på ditt kreditkortsutdrag är en stark indikation på att ditt kortnummer har komprometterats och använts för obehöriga köp, vilket är typiskt för kreditkortsbedrägeri.",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 8,
                            CorrectAnswer = "Utbildning i digital säkerhet för alla anställda",
                            Explanation = "Utbildning i digital säkerhet är avgörande för att hjälpa anställda att känna igen och undvika säkerhetshot som phishing, vilket är en vanlig attackvektor",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 9,
                            CorrectAnswer = "Implementera en policy för lösenordskomplexitet som kräver automatiska lösenordsändringar var 90:e dag",
                            Explanation = "En automatisk policy för lösenordsändring tvingar fram regelbundna uppdateringar och säkerställer att lösenorden hålls starka och svåra att knäcka, vilket minskar risken för obehörig åtkomst.",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 10,
                            CorrectAnswer = "Utrusta alla anställdas enheter med VPN (Virtual Private Network)-tjänster",
                            Explanation = "Genom att använda VPN kan anställda säkert ansluta till företagets nätverk även från otrygga Wi-Fi-nätverk, vilket krypterar dataöverföring och skyddar mot avlyssning och andra cyberhot.",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 11,
                            CorrectAnswer = "Installera och uppdatera regelbundet e-postsäkerhetslösningar som filtrerar bort skadlig programvara och misstänkta länkar",
                            Explanation = "Avancerade e-postsäkerhetslösningar kan effektivt identifiera och blockera skadlig programvara och phishing-försök, vilket minskar risken för att anställda oavsiktligt exponerar företagets system och data för cyberhot.",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 12,
                            CorrectAnswer = "Informera alla användare om sårbarheten och rekommendera temporära skyddsåtgärder",
                            Explanation = "Transparent kommunikation och rådgivning om tillfälliga åtgärder är avgörande för att skydda användarna medan en permanent lösning utvecklas.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 13,
                            CorrectAnswer = "Organiserade cyberbrottsliga grupper",
                            Explanation = "DDoS-attacker kräver ofta betydande resurser och koordinering, vilket är karakteristiskt för organiserade cyberbrottsliga grupper.",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 14,
                            CorrectAnswer = "Införa striktare lösenordspolicyer och tvåfaktorsautentisering för fjärråtkomst",
                            Explanation = "Stärkt autentisering är kritisk för att säkra fjärråtkomst och skydda mot obehörig åtkomst i en distribuerad arbetsmiljö.",
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 15,
                            CorrectAnswer = "Ransomware",
                            Explanation = "Ransomware-angrepp involverar kryptering av offerdata och kräver lösen för dekryptering, vilket är särskilt skadligt för kritiska sektorer som hälsovård.",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 16,
                            CorrectAnswer = "Ransomware",
                            Explanation = "Maersk utsattes för NotPetya ransomware-angreppet, som ledde till omfattande störningar och förluster genom att kryptera företagets globala system.Maersk rapporterade att företaget led ekonomiska förluster på grund av NotPetya ransomware-angreppet som uppskattades till cirka 300 miljoner USD. Denna siffra reflekterar de omfattande kostnaderna för störningar i deras globala verksamheter, återställande av system och data, samt förlust av affärer under tiden systemen var nere. NotPetya-angreppet anses vara ett av de mest kostsamma cyberangreppen mot ett enskilt företag och tjänar som en kraftfull påminnelse om de potentiella konsekvenserna av cyberhot.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 17,
                            CorrectAnswer = "Cyberspionage",
                            Explanation = "Cyberspionage avser aktiviteter där aktörer, ofta statliga, engagerar sig i övervakning och datainsamling genom cybermedel för att erhålla hemlig information utan målets medgivande, typiskt för politiska, militära eller ekonomiska fördelar. I takt med att cyberspionage blir allt mer sofistikerat, krävs det starkare skyddsmekanismer för att säkra känslig information. Ett av de mest effektiva sätten att skydda data är genom kryptering. Denna teknik säkerställer att informationen förblir privat, även om den skulle hamna i fel händer.",
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 18,
                            CorrectAnswer = "Öka användningen av kryptering för all intern och extern kommunikation",
                            Explanation = "Kryptering är en kraftfull metod för att skydda känslig information under överföring och lagring, vilket gör det extremt svårt för obehöriga att få tillgång till och förstå informationen, även om de lyckas avlyssna kommunikationen.",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 19,
                            CorrectAnswer = "Implementera ett omfattande program för beteendeanalys och anomalidetektering",
                            Explanation = "Program för beteendeanalys och anomalidetektering kan effektivt identifiera ovanligt beteende eller aktiviteter som kan tyda på insiderhot eller obehörig åtkomst till känslig information, vilket är ett kritiskt steg för att förhindra cyberspionage. Mjukvarusårbarheter är ofta den svaga länken som utnyttjas i cyberspionageattacker. Utan snabba och regelbundna säkerhetsuppdateringar och patchar, kan dessa sårbarheter lämna dörrarna vidöppna för angripare. Att hålla programvara och system uppdaterade är en grundläggande men kritisk del av ett effektivt cybersäkerhetsförsvar.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 20,
                            CorrectAnswer = "Hålla all mjukvara och operativsystem uppdaterade med de senaste säkerhetspatcharna",
                            Explanation = "Regelbundna uppdateringar och patchning av mjukvara och operativsystem är avgörande för att stänga säkerhetshål som annars kan utnyttjas av cyberspioner. Detta minskar risken för intrång och dataläckor avsevärt.",
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 21,
                            CorrectAnswer = "Riktade cyberattacker",
                            Explanation = "Riktade cyberattacker som utnyttjar noll-dagars Zero-day sårbarheter är en avancerad metod för cyberspionage där angriparen specifikt riktar in sig på ett mål för att komma åt känslig information eller data genom att utnyttja tidigare okända sårbarheter i programvara.",
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 22,
                            CorrectAnswer = "Säkerhetsskyddslagen",
                            Explanation = "Säkerhetsskyddslagen är en svensk lagstiftning som syftar till att skydda nationellt känslig information från spioneri, sabotage, terroristbrott och andra säkerhetshot. Lagen ställer krav på säkerhetsskyddsåtgärder för verksamheter av betydelse för Sveriges säkerhet.",
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 23,
                            CorrectAnswer = "Statssponsrade hackers",
                            Explanation = "Statssponsrade hackers är aktörer som arbetar på uppdrag av eller med stöd från en regering för att genomföra cyberspionage, ofta riktat mot utländska intressen, organisationer eller regeringar för att få strategiska fördelar.",
                            QuestionId = 23
                        });
                });

            modelBuilder.Entity("ValhallaVault.Models.SubcategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SegmentId = 1,
                            SubCategoryName = "Kreditkortsbedrägeri"
                        },
                        new
                        {
                            Id = 2,
                            SegmentId = 1,
                            SubCategoryName = "Romansbedrägeri"
                        },
                        new
                        {
                            Id = 3,
                            SegmentId = 1,
                            SubCategoryName = "Investeringsbedrägeri"
                        },
                        new
                        {
                            Id = 4,
                            SegmentId = 1,
                            SubCategoryName = "Telefonbedrägeri"
                        },
                        new
                        {
                            Id = 5,
                            SegmentId = 2,
                            SubCategoryName = "Bedrägerier i hemmet"
                        },
                        new
                        {
                            Id = 6,
                            SegmentId = 2,
                            SubCategoryName = "Identitetsstöld"
                        },
                        new
                        {
                            Id = 7,
                            SegmentId = 2,
                            SubCategoryName = "Nätfiske och bluffmejl"
                        },
                        new
                        {
                            Id = 8,
                            SegmentId = 2,
                            SubCategoryName = "Investeringsbedrägeri på nätet"
                        },
                        new
                        {
                            Id = 9,
                            SegmentId = 3,
                            SubCategoryName = "Abonnemangsfällor och falska fakturor"
                        },
                        new
                        {
                            Id = 10,
                            SegmentId = 3,
                            SubCategoryName = "Ransomware"
                        },
                        new
                        {
                            Id = 11,
                            SegmentId = 3,
                            SubCategoryName = "Statistik och förhållningssätt"
                        },
                        new
                        {
                            Id = 12,
                            SegmentId = 4,
                            SubCategoryName = "Digital säkerhet på företag"
                        },
                        new
                        {
                            Id = 13,
                            SegmentId = 4,
                            SubCategoryName = "Risker och beredskap"
                        },
                        new
                        {
                            Id = 14,
                            SegmentId = 4,
                            SubCategoryName = "Aktörer inom cyberbrott"
                        },
                        new
                        {
                            Id = 15,
                            SegmentId = 4,
                            SubCategoryName = "Ökad digital närvaro och distansarbete"
                        },
                        new
                        {
                            Id = 16,
                            SegmentId = 4,
                            SubCategoryName = "Cyberangrepp mot känsliga sektorer"
                        },
                        new
                        {
                            Id = 17,
                            SegmentId = 4,
                            SubCategoryName = "Cyberrånet mot Mersk "
                        },
                        new
                        {
                            Id = 18,
                            SegmentId = 5,
                            SubCategoryName = "Social engineering"
                        },
                        new
                        {
                            Id = 19,
                            SegmentId = 5,
                            SubCategoryName = "Nätfiske och skräppost"
                        },
                        new
                        {
                            Id = 20,
                            SegmentId = 5,
                            SubCategoryName = "Vishing"
                        },
                        new
                        {
                            Id = 21,
                            SegmentId = 5,
                            SubCategoryName = "Varning för vishing"
                        },
                        new
                        {
                            Id = 22,
                            SegmentId = 5,
                            SubCategoryName = "Identifiera VD-mejl"
                        },
                        new
                        {
                            Id = 23,
                            SegmentId = 5,
                            SubCategoryName = "Öneangrepp och presentkortsbluffar"
                        },
                        new
                        {
                            Id = 24,
                            SegmentId = 6,
                            SubCategoryName = "Virus, maskar och trojaner"
                        },
                        new
                        {
                            Id = 25,
                            SegmentId = 6,
                            SubCategoryName = "Så kan det gå till"
                        },
                        new
                        {
                            Id = 26,
                            SegmentId = 6,
                            SubCategoryName = "Nätverksintrång"
                        },
                        new
                        {
                            Id = 27,
                            SegmentId = 6,
                            SubCategoryName = "Dataintrång"
                        },
                        new
                        {
                            Id = 28,
                            SegmentId = 6,
                            SubCategoryName = "Hackad!"
                        },
                        new
                        {
                            Id = 29,
                            SegmentId = 6,
                            SubCategoryName = "Vägarna in"
                        },
                        new
                        {
                            Id = 30,
                            SegmentId = 7,
                            SubCategoryName = "Utpressningsvirus"
                        },
                        new
                        {
                            Id = 31,
                            SegmentId = 7,
                            SubCategoryName = "Attacker mot servrar"
                        },
                        new
                        {
                            Id = 32,
                            SegmentId = 7,
                            SubCategoryName = "Cyberangrepp i Norden"
                        },
                        new
                        {
                            Id = 33,
                            SegmentId = 7,
                            SubCategoryName = "It-brottslingarnas verktyg"
                        },
                        new
                        {
                            Id = 34,
                            SegmentId = 7,
                            SubCategoryName = "Mirai, Wannacry och fallet Düsseldorf"
                        },
                        new
                        {
                            Id = 35,
                            SegmentId = 7,
                            SubCategoryName = "De sårbara molnen"
                        },
                        new
                        {
                            Id = 36,
                            SegmentId = 8,
                            SubCategoryName = "Allmänt om cyberspionage"
                        },
                        new
                        {
                            Id = 37,
                            SegmentId = 8,
                            SubCategoryName = "Metoder för cyberspionage"
                        },
                        new
                        {
                            Id = 38,
                            SegmentId = 8,
                            SubCategoryName = "Säkerhetsskyddslagen"
                        },
                        new
                        {
                            Id = 39,
                            SegmentId = 8,
                            SubCategoryName = "Cyberspionagets aktörer"
                        },
                        new
                        {
                            Id = 40,
                            SegmentId = 9,
                            SubCategoryName = "Värvningsförsök"
                        },
                        new
                        {
                            Id = 41,
                            SegmentId = 9,
                            SubCategoryName = "Affärsspionage"
                        },
                        new
                        {
                            Id = 42,
                            SegmentId = 9,
                            SubCategoryName = "Påverkanskampanjer"
                        },
                        new
                        {
                            Id = 43,
                            SegmentId = 10,
                            SubCategoryName = "Svensk underrättelsetjänst och cyberförsvar"
                        },
                        new
                        {
                            Id = 44,
                            SegmentId = 10,
                            SubCategoryName = "Signalspaning, informationssäkerhet och 5G"
                        },
                        new
                        {
                            Id = 45,
                            SegmentId = 10,
                            SubCategoryName = "Samverkan mot cyberspionage"
                        });
                });

            modelBuilder.Entity("ValhallaVault.Models.UserResult", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ResultId");

                    b.HasIndex("ResultId");

                    b.ToTable("UserResults");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ValhallaVault.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ValhallaVault.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValhallaVault.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ValhallaVault.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ValhallaVault.Models.QuestionModel", b =>
                {
                    b.HasOne("ValhallaVault.Models.SubcategoryModel", "SubCategory")
                        .WithMany("Questions")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("ValhallaVault.Models.ResultModel", b =>
                {
                    b.HasOne("ValhallaVault.Models.QuestionModel", "Question")
                        .WithMany("Results")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ValhallaVault.Models.SegmentModel", b =>
                {
                    b.HasOne("ValhallaVault.Models.CategoryModel", "Category")
                        .WithMany("Segments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ValhallaVault.Models.SolutionModel", b =>
                {
                    b.HasOne("ValhallaVault.Models.QuestionModel", "Question")
                        .WithOne("Solution")
                        .HasForeignKey("ValhallaVault.Models.SolutionModel", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ValhallaVault.Models.SubcategoryModel", b =>
                {
                    b.HasOne("ValhallaVault.Models.SegmentModel", "Segment")
                        .WithMany("Subcategories")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("ValhallaVault.Models.UserResult", b =>
                {
                    b.HasOne("ValhallaVault.Models.ResultModel", "Result")
                        .WithMany("UserResults")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValhallaVault.Data.ApplicationUser", "User")
                        .WithMany("UserResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValhallaVault.Data.ApplicationUser", b =>
                {
                    b.Navigation("UserResults");
                });

            modelBuilder.Entity("ValhallaVault.Models.CategoryModel", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("ValhallaVault.Models.QuestionModel", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("Solution")
                        .IsRequired();
                });

            modelBuilder.Entity("ValhallaVault.Models.ResultModel", b =>
                {
                    b.Navigation("UserResults");
                });

            modelBuilder.Entity("ValhallaVault.Models.SegmentModel", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("ValhallaVault.Models.SubcategoryModel", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
